### ISSUE TITLE
Show subject metadata?

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/Talk-archiver#17]
The old Talk pages don't seem to make subject metadata visible eg. https://talk.sciencegossip.org/#/subjects/ASC00005uy

At the moment, the archive pages don't show any metadata at all.
https://talk.sciencegossip.org/subjects/ASC0001ig3/

Should subject metadata be visible to users of these pages?

**Comment by camallen** [comment]
i'd say no for feature parity but if it's an easy feature to add and you want to do it, great!

**Comment by eatyourgreens** [comment]
Subject metadata is available from `/api/subjects` eg. https://talk.sciencegossip.org/api/subjects/ASC0001vvm.json (this link is easier to use if you open it with the JSON viewer in Firefox.)

I’m ok with people using that to get metadata for archived subjects. Otherwise, I think each project might need its own, individual metadata view.

**Comment by camallen** [comment]
that's a great solution @eatyourgreens

**Comment by eatyourgreens** [comment]
#65 should take care of this, once it's implemented.
