### ISSUE TITLE
Cyclone Center has discussions based around groups

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/Talk-archiver#67]
https://talk.cyclonecenter.org/#/groups/GCC00000ay

Cyclone Center has discussion comments for Groups, where a group appears to be a set of subjects from the same storm.
The discussions export `cyclone_center_discussions.json` contains discussions where the focus is a group eg.
```json
{"_id":"GCC00000ay","type":"CycloneCenterGroup","name":"GCC00000ay","base_type":"Group", "subjects": […]}
```
Maybe we can build discussion pages for these with URLs like `/groups/GCC00000ay`. It's likely that the discussion summary doesn't contain all the subjects for that group, but only the first 5.

**Comment by camallen** [comment]
I've spoken to Chris about this, we should do the simplest thing that can work and we're ok to miss content for this site. If the effort takes longer than 1-2 days to resolve we can avoid doing this work.

**Comment by trouille** [comment]
@camallen I probably missed the resolution in the thread. What's the status/decision for this? Leave as is?

**Comment by camallen** [comment]
Yes - resolution was to avoid rebuilding cyclone center talk as it's a complex data structure we have to sink time into.
