### ISSUE TITLE
Tagged collections aren't listed at /tags/{tagName}/collections.html

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/Talk-archiver#75]
Penguin Watch:
> https://talk.penguinwatch.org/tags/egg/collections.html - shows no collections

Tagged collections seem to be broken in general. This Galaxy Zoo page is also empty, but should list 6 collections.
https://talk.galaxyzoo.org/tags/edgeon/collections.html

EDIT: here's another example of broken collection tags.
https://talk.milkywayproject.org/tags/starcluster/

This line should be `tag.userCollections` not `tag.collections` (`collections` is already used by Eleventy.) I don't know how many sites are affected by this bug.
https://github.com/zooniverse/Talk-archiver/blob/b5eb813082970ea249111ec44a3f28ed95160e79/src/tags/userTags/collections.njk#L15

_Originally posted by @eatyourgreens in https://github.com/zooniverse/Talk-archiver/issues/56#issuecomment-673435820_

**Comment by eatyourgreens** [comment]
Fixed by c600a7fb226eadabedf29bf8af321fdb0c44d36f

**Comment by camallen** [comment]
are we tracking which sites have been rebuilt to fix this bug. 

I assume we are re-running them all but I can look into more data digging to get a list of projects that would need more than the default of 6 tagged collections if required.

**Comment by eatyourgreens** [comment]
I'm working through the big projects listed in #56. Mostly done now. ![A handwritten list of projects that have been processed. Galaxy Zoo, Milky Way Project, Penguin Watch, Planet Four, Planet Hunters, Operation War Diary, Disk Detective.](https://user-images.githubusercontent.com/59547/90156976-0d322380-dd85-11ea-971c-ba1840619b90.jpeg)

**Comment by eatyourgreens** [comment]
Ok, everything in #56 except Chimp & See has been re-built and published. C&S requires #74, which doesn't have the fix (yet.)

**Comment by eatyourgreens** [comment]
Update: I've merged #74 and updated Chimp & See so all the projects listed in #56 should now be fixed.

**Comment by eatyourgreens** [comment]
I think we can add `subject.location.thumbnail` as another possible value for `previewLocation` and also a rule to pass through URLs beginning with `https://ww.galaxyzoo.org`.
https://github.com/zooniverse/Talk-archiver/blob/33f3a876bfab77fa42e9c86a5ec3e0831ac21641/src/components/subjectImage.js#L17-L29

Development and deployment for these big projects is happening with the branch in #72. I should probably just merge it to master. It's been used to build everything listed in #56.

**Comment by eatyourgreens** [comment]
Randomly checking popular tags in the projects in #55, I’ve yet to find a tag that has more than 6 collections.

**Comment by eatyourgreens** [comment]
Asteroid Zoo looks like the next one to prioritise. https://talk.asteroidzoo.org/tags/asteroid/
