### ISSUE TITLE
Disk Detective collections page missing subject ids on listed subjects

### ISSUE THREAD

**Issue by srallen** [zooniverse/Talk-archiver#76]
This is likely a non-blocking issue, but on the Disk Detective collections page, the subjects displayed nearly look identical, which makes browsing the list nearly useless on the new version of the page. The original Ouroboros Talk page displayed the subject id which aids in distinguishing each subject:

![Screen Shot 2020-08-13 at 10 37 52 AM](https://user-images.githubusercontent.com/5016731/90155869-739d4e80-dd51-11ea-92a7-9c32c0230eea.png)

However, on the archive version that is missing:

<img width="1411" alt="Screen Shot 2020-08-13 at 10 37 59 AM" src="https://user-images.githubusercontent.com/5016731/90155924-81eb6a80-dd51-11ea-8919-81e4d03a703c.png">

The links work as expected to each subject.

**Comment by srallen** [comment]
Another non-blocking suggestion: lazy loading for images. This page was pretty slow to load: https://talk.diskdetective.org/tags/multiple/subjects.html

**Comment by camallen** [comment]
While lazy loading and UI improvements would help - I think we're too far down the track for this improvement now, our focus is on finalizing this conversion and decommissioning the associated API. Our aim was to archive our user generated content for posterity which we've done. 

Jim - if you feel like this is something worth while then go for it.

**Comment by eatyourgreens** [comment]
Lazy loading is implemented already!
https://github.com/zooniverse/Talk-archiver/blob/b5eb813082970ea249111ec44a3f28ed95160e79/src/components/subjectImage.js#L3-L5

**Comment by srallen** [comment]
I'm not sure if that's functioning as expected. The page I linked to, I disabled the cache so it was like first load, and it immediately requested all the images:

![Screen Shot 2020-08-13 at 11 53 31 AM](https://user-images.githubusercontent.com/5016731/90163412-aea47f80-dd5b-11ea-84c9-7a0f54c86443.png)

But as I acknowledged, non-blocking.

**Comment by eatyourgreens** [comment]
Interesting. I’ve been seeing loading prioritised for images that are in the viewport but haven’t checked how many total requests are made. 

We’re likely to see more of this on these larger projects, where lists of subjects can grow into the tens of thousands.

**Comment by eatyourgreens** [comment]
`loading` isn’t supported by Safari (or IE) but I could add a polyfill to these larger sites. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-loading

Changes to the JS would mean rebuilding every page, though.

**Comment by eatyourgreens** [comment]
On this page, in Firefox 84, network requests aren't made for images until you scroll down and bring them into the viewport. I've been assuming that Chrome etc. implement the same spec for lazy loading but haven't checked.
https://talk.galaxyzoo.org/collections/CGZS0002cc/

**Comment by eatyourgreens** [comment]
Re. the original issue, we could make the collection JSON more visible, like we did for subject pages. 

I think the trade-off is the usability of collections vs. keeping Ouroboros running longer while we make the changes.

**Comment by srallen** [comment]
That Galaxy Zoo page isn't enough requests to hit the performance problem I'm seeing. Try the page I originally reported about which is making thousands of requests initially in Chrome and taking nearly 5 minutes to load: https://talk.diskdetective.org/tags/multiple/subjects.html

Firefox handled it as I would expect, only initiating ~300 requests at the start taking only 8 seconds. It seems like a difference in the implementation of the spec?

**Comment by srallen** [comment]
Resolving either of these, though, as I have said a few times, is non-blocking, so if the goal here is just purely archived static pages, then the goal has been accomplished. An initial 5 minute load time doesn't absolutely stop anyone from accessing the page if they're willing to wait. Feel free to close.

**Comment by eatyourgreens** [comment]
One of the problems is that Disk Detective uses PNG images, so can't use our thumbnail service. I did some comparisons in Chrome and Firefox, looking at Disk Detective (PNG subjects) and Snapshot Serengeti (JPG subjects.) Chrome makes more requests and is slower (as expected) for Disk Detective. Both browsers request images that are outside the initial viewport on the larger page.

https://talk.diskdetective.org/tags/multiple/subjects.html (30,951 images)
Firefox: 62 requests, 1.67 MB downloaded, 5s load time.
Chrome: 711 requests, 9.7MB downloaded, 2.6 min load time.
![Network performance of a Disk Detective page with 30,951 PNG images in Firefox.](https://user-images.githubusercontent.com/59547/90375850-6cd24c80-e06d-11ea-9748-46bce9b1730c.png)

![Network performance of a Disk Detective page with 30,951 PNG images in Chrome.](https://user-images.githubusercontent.com/59547/90375757-4ad8ca00-e06d-11ea-90c1-05dc3f6909a6.png)

https://talk.snapshotserengeti.org/users/maricksu/comments.html (12,569 images)
Firefox: 9 requests, 877k, 5s load time
Chrome: 46 requests, 1MB , 37s load time
![Network performance of a Snapshot Serengeti page with 12,569 JPG images in Firefox.](https://user-images.githubusercontent.com/59547/90376164-ec601b80-e06d-11ea-9146-4222a2b6e154.png)

![Network performance of a Snapshot Serengeti page with 12,569 JPG images in Chrome.](https://user-images.githubusercontent.com/59547/90376568-9475e480-e06e-11ea-97e5-ea0156bc2249.png)

**Comment by eatyourgreens** [comment]
Worth noting that the tag, like all resources, is also available as JSON.
https://talk.diskdetective.org/api/tags/multiple.json

**Comment by eatyourgreens** [comment]
Running Lighthouse on one of the large Galaxy Zoo pages (~25k subjects) threw an error I've never seen before, because the page is so large.
![A screenshot of Lighthouse, showing four red question marks where the scores should be.](https://user-images.githubusercontent.com/59547/90397106-40c7c300-e08f-11ea-8c85-eceec4d0fcf9.png)

**Comment by eatyourgreens** [comment]
Chimp & See collections seem to max out at 500 subjects eg. https://talk.chimpandsee.org/collections/CCPL0000ie/ (from #73) Is there a limit on collections, which doesn't apply to tags?

**Comment by camallen** [comment]
Closing this issue for now - if folks want to rebuild the sites with a pollyfill for safari great. Otherwise folks can use a compliant browser to access pages like this. Not great but the content is technically available so our archive goal is acheived
