### ISSUE TITLE
Some filenames aren't compatible with Azure Storage

### ISSUE THREAD

**Issue by adammcmaster** [zooniverse/Talk-archiver#78]
Azure storage has [more restrictive rules](https://docs.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata#blob-names) on filenames than S3. In our case, it seems some files/directories have periods at the end of their names, which is not allowed. (The docs say to avoid it, but `azcopy` encounters a 403 error when it tries to PUT those files so they appear to be disallowed completely.)

Example failing request: `PUT https://zooniversestatic.blob.core.windows.net/$web/talk.chicagowildlifewatch.org/users/Salma_S./comments.html`

Affected sites so far:

- radiotalk.galaxyzoo.org/
- talk.chicagowildlifewatch.org/
- talk.diskdetective.org/
- talk.galaxyzoo.org/
- talk.planethunters.org/
- talk.snapshotserengeti.org/
- talk.wormwatchlab.org/

See also [Slack discussion](https://zooniverse.slack.com/archives/C0138Q1LVCL/p1597753228260100). Summary:
- We will need to rewrite these filenames and rebuild (or compile a full list of affected files and rename them on S3, whichever all be quickest).
- @camallen suggests that we set up an Nginx rewrite rule to avoid breaking existing links.

**Comment by camallen** [comment]
closed by #85 i've manually run the remap scripts and our nginx proxy now serves the invalid char URLs from the remapped files via https://github.com/zooniverse/static/pull/179
